BlockchainSettingsService: 
    Keys:
        settings-key: BlockchainSettingsService-Keys
        types: 
            - JsonArray
    Db: 
        LogsConnectionString: 
            settings-key: BlockchainSettingsService-Db-Logs
            types: 
                - AzureTableStorage
                - Tag
        DataConnectionString:
            settings-key: BlockchainSettingsService-Db-Data
            types:
                - AzureTableStorage
                - Tag
    RedisCache: 
        RedisConfiguration: 
            settings-key: BlockchainSettingsService-Redis
            types:
                - Redis
                - Tag
        InstanceName: 
            settings-key: BlockchainSettingsService-RedisInstanceName
            types:
                - Tag
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: BlockchainSettingsService-MonitoringUrl
        types:
            - AzureTableStorage 
            - Tag
SlackNotifications: 
    AzureQueue:
        ConnectionString:
            settings-key: BlockchainSettingsService-Slack-Azure
            types: 
                - AzureTableStorage
                - Tag
        QueueName: 
            settings-key: BlockchainSettingsService-QueueName
            types:
                - Tag
    ThrottlingLimitSeconds: 
        settings-key: BlockchainSettingsService-ThrottlingLimitSeconds
        types:
            - Tag
