BlockchainSettingsService: 
    Keys:
        settings-key: BlockchainSettingsService-Keys
        types: 
            - JsonArray
    Db: 
        LogsConnectionString: 
            settings-key: BlockchainSettingsService-Db-Logs
            types: 
                - AzureTableStorage
        DataConnectionString:
            settings-key: BlockchainSettingsService-Db-Data
            types:
                - AzureTableStorage
    RedisCache: 
        RedisConfiguration: 
            settings-key: BlockchainSettingsService-Redis
            types:
                - Redis
        InstanceName: 
            settings-key: BlockchainSettingsService-RedisInstanceName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
        types:
            - AzureTableStorage 
SlackNotifications: 
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types: 
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName
    ThrottlingLimitSeconds: 
        settings-key: BlockchainSettingsService-ThrottlingLimitSeconds
